print("Hello, World!")
print("This is a practice file.")
print("Let's learn Python together!")
print("Python is a versatile programming language.")
print("Practice makes perfect!")
print("Keep coding and improving your skills.")
print("Don't be afraid to make mistakes; they are part of the learning process.")
print("Remember to have fun while coding!")